#!/usr/bin/env python3
"""
Export the pool Pulse composes Backstory categories from (T-0079).

Pulse runs in a browser and cannot read xlsx or run Python, so everything it needs is
exported to one JSON file beside the other Pulse data:

  python3 editorial/export_for_pulse.py        # writes ntk-pulse/data/backstory-pool.json

Two pools, one shape:
  matrix     every linked, not-dead object in the Object Matrix. Approved by definition.
  candidate  the "Lens candidates" tab of NTK_Backstory_Candidates.xlsx. Approved only
             where the editor put Y in the Approve column. Pulse can also approve one
             in place, which a category record carries (and CI honours).

Each object carries the lenses it belongs to, computed here by the same rules as
build_backstory.lens_select, so the browser never re-implements lens matching. The file
records the sha256 of both workbooks; scripts/rot.sh tickets compare against it, so a
matrix edit that is not re-exported shows up as rot.
"""
import hashlib, json, sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import openpyxl
import build_backstory as bb

ROOT = Path(bb.ROOT)
CANDS = ROOT / "editorial" / "NTK_Backstory_Candidates.xlsx"
OUT = ROOT / "ntk-pulse" / "data" / "backstory-pool.json"
MATRIX_PATH = Path(bb.MATRIX)


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def main():
    spec = json.load(open(bb.LENSES))
    notes = bb.load_notes()
    health = bb.load_health()
    out = []
    for lst in bb.load_objects().values():
        for o in lst:
            if not o["source_url"]:
                continue          # no live link, not eligible (T-0065)
            n = notes.get(o["object_id"], {})
            h = health.get(o["source_url"], {})
            out.append({
                "id": o["object_id"], "pool": "matrix", "approved": True,
                "title": o["title"], "author": o["author"], "year": o["year"], "sort": o["_sort"],
                "source": o["source"], "url": o["source_url"],
                "row": o["_row"], "subgenre": o["_subgenre"],
                "lenses": bb.lens_names(o, spec),
                "line": n.get("line", ""), "about": n.get("about", ""),
                "text_verified": bool(n.get("verified")),
                "link_status": h.get("status", "unchecked"),
            })
    wb = openpyxl.load_workbook(CANDS, read_only=True)
    if "Lens candidates" in wb.sheetnames:
        rows = list(wb["Lens candidates"].iter_rows(values_only=True))
        ix = {h: i for i, h in enumerate(rows[0])}
        for r in rows[1:]:
            if not r[ix["Title"]]:
                continue
            sort = str(r[ix["Sort Date"]] or "")
            out.append({
                "id": bb.slug(sort + "-" + str(r[ix["Title"]])), "pool": "candidate",
                "approved": str(r[ix["Approve"]] or "").strip().lower() in ("y", "yes", "true"),
                "title": r[ix["Title"]], "author": r[ix["Author"]] or "", "year": sort[:4], "sort": sort,
                "source": r[ix["Source"]] or "", "url": r[ix["Source URL"]] or "",
                "row": r[ix["NTK Row"]] or "", "subgenre": r[ix["Sub-genre"]] or "",
                "lenses": [r[ix["Lens"]]] if r[ix["Lens"]] else [],
                "line": "", "about": "", "text_verified": False,
                "link_status": r[ix["Status"]] or "unchecked",
                "why": r[ix["Why it's here"]] or "", "note": r[ix["Notes"]] or "",
            })
    out.sort(key=lambda o: o["sort"])
    doc = {
        "_comment": "Generated by editorial/export_for_pulse.py. Do not edit. Pulse reads this to compose Backstory categories (T-0079).",
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "matrix_sha256": sha(MATRIX_PATH), "candidates_sha256": sha(CANDS),
        "notes_sha256": sha(bb.NOTES), "lenses_sha256": sha(bb.LENSES),
        "vocab": {"subgenres": [{"name": sg, "row": r["id"], "row_title": r["title"]} for r in json.load(open(ROOT / "editorial" / "backstory-rows.json"))["rows"] for sg in r.get("subgenres", [])]},
        "lenses": {k: {"story_terms": v.get("story_terms", []), "story_terms_cs": v.get("story_terms_cs", [])}
                   for k, v in spec.items() if not k.startswith("_")},
        "objects": out,
    }
    OUT.write_text(json.dumps(doc, ensure_ascii=False, separators=(",", ":")) + "\n")
    by = {}
    for o in out:
        by.setdefault(o["pool"], 0); by[o["pool"]] += 1
    print(f"wrote {OUT.relative_to(ROOT)}: {by}, {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
